import { 
  UtensilsCrossed, 
  Coffee, 
  Pizza, 
  Scissors, 
  Sparkles, 
  Flower2, 
  Building2, 
  Home, 
  SunMedium, 
  Stethoscope, 
  Activity, 
  ShieldPlus, 
  Dumbbell, 
  ShoppingBag, 
  Store, 
  Briefcase, 
  Car, 
  Music, 
  Layers,
  LucideIcon
} from 'lucide-react';
import { BusinessCategory } from './types';

export interface CategoryDefinition {
  id: BusinessCategory;
  label: string;
  categoryGroup: 'food' | 'beauty' | 'hospitality' | 'health' | 'retail' | 'services';
  groupLabel: string;
  desc: string;
  icon: LucideIcon;
  defaultCtaLabel: string;
  badgeLabel: string;
}

export const CATEGORY_GROUPS = [
  { id: 'all', label: 'Tutti i Settori' },
  { id: 'food', label: 'Food & Beverage' },
  { id: 'beauty', label: 'Beauty & Wellness' },
  { id: 'hospitality', label: 'Hospitality & Turismo' },
  { id: 'health', label: 'Salute & Cura' },
  { id: 'retail', label: 'Retail & Shopping' },
  { id: 'services', label: 'Servizi & Professioni' },
] as const;

export const CATEGORIES: CategoryDefinition[] = [
  {
    id: 'restaurant',
    label: 'Ristorante & Bistrot',
    categoryGroup: 'food',
    groupLabel: 'Food & Beverage',
    desc: 'Menù digitale, chiamata cameriere, recensioni e AI Sommelier',
    icon: UtensilsCrossed,
    defaultCtaLabel: 'Consulta Menù Digitale',
    badgeLabel: 'Ristorazione',
  },
  {
    id: 'bar',
    label: 'Bar & Caffetteria',
    categoryGroup: 'food',
    groupLabel: 'Food & Beverage',
    desc: 'Listino colazioni, caffetteria, dolci, Wi-Fi rapido e fidelity',
    icon: Coffee,
    defaultCtaLabel: 'Listino & Colazioni',
    badgeLabel: 'Bar & Caffè',
  },
  {
    id: 'pizzeria',
    label: 'Pizzeria & Pub',
    categoryGroup: 'food',
    groupLabel: 'Food & Beverage',
    desc: 'Pizze gourmet, birre artigianali, chiamata sala e sconti',
    icon: Pizza,
    defaultCtaLabel: 'Menù Pizze & Birre',
    badgeLabel: 'Pizzeria & Pub',
  },
  {
    id: 'salon',
    label: 'Salone Parrucchiere',
    categoryGroup: 'beauty',
    groupLabel: 'Beauty & Wellness',
    desc: 'Prenotazioni piega e taglio, card timbri e Wi-Fi clienti',
    icon: Scissors,
    defaultCtaLabel: 'Prenota un Appuntamento',
    badgeLabel: 'Hair Studio',
  },
  {
    id: 'barber',
    label: 'Barber Shop & Grooming',
    categoryGroup: 'beauty',
    groupLabel: 'Beauty & Wellness',
    desc: 'Taglio barba & capelli, fidelity pass e recensioni 5 stelle',
    icon: Sparkles,
    defaultCtaLabel: 'Prenota il Tuo Taglio',
    badgeLabel: 'Barber Shop',
  },
  {
    id: 'beauty',
    label: 'Centro Estetico & SPA',
    categoryGroup: 'beauty',
    groupLabel: 'Beauty & Wellness',
    desc: 'Trattamenti viso/corpo, massaggi relax, listino e contatti',
    icon: Flower2,
    defaultCtaLabel: 'Listino Trattamenti',
    badgeLabel: 'Estetica & SPA',
  },
  {
    id: 'hotel',
    label: 'Hotel & Resort',
    categoryGroup: 'hospitality',
    groupLabel: 'Hospitality & Turismo',
    desc: 'Wi-Fi automatico, chiamata reception, guida del territorio e room service',
    icon: Building2,
    defaultCtaLabel: 'Contatta la Reception',
    badgeLabel: 'Hotel & Resort',
  },
  {
    id: 'bnb',
    label: 'B&B & Casa Vacanze',
    categoryGroup: 'hospitality',
    groupLabel: 'Hospitality & Turismo',
    desc: 'Self check-in, Wi-Fi 1-tap, contatti host e consigli locali',
    icon: Home,
    defaultCtaLabel: 'Guida per gli Ospiti',
    badgeLabel: 'B&B & Ospitalità',
  },
  {
    id: 'beach_club',
    label: 'Lido & Beach Club',
    categoryGroup: 'hospitality',
    groupLabel: 'Hospitality & Turismo',
    desc: 'Ordini sotto l\'ombrellone, bar spiaggia e prenotazione lettini',
    icon: SunMedium,
    defaultCtaLabel: 'Ordina all\'Ombrellone',
    badgeLabel: 'Beach Club',
  },
  {
    id: 'medical',
    label: 'Studio Medico',
    categoryGroup: 'health',
    groupLabel: 'Salute & Cura',
    desc: 'Accoglienza in sala d\'attesa, info specialistiche e orari',
    icon: Stethoscope,
    defaultCtaLabel: 'Info Visite & Prestazioni',
    badgeLabel: 'Studio Medico',
  },
  {
    id: 'dental',
    label: 'Studio Odontoiatrico',
    categoryGroup: 'health',
    groupLabel: 'Salute & Cura',
    desc: 'Prima visita, igiene dentale, WhatsApp di segreteria e recensioni',
    icon: Activity,
    defaultCtaLabel: 'Prenota Prima Visita',
    badgeLabel: 'Odontoiatria',
  },
  {
    id: 'pharmacy',
    label: 'Farmacia & Parafarmacia',
    categoryGroup: 'health',
    groupLabel: 'Salute & Cura',
    desc: 'Turni notturni, servizi di autoanalisi, canale WhatsApp per ricette',
    icon: ShieldPlus,
    defaultCtaLabel: 'Invia Ricetta / WhatsApp',
    badgeLabel: 'Farmacia',
  },
  {
    id: 'fitness',
    label: 'Palestra & Centro Fitness',
    categoryGroup: 'health',
    groupLabel: 'Salute & Cura',
    desc: 'Orario corsi, prova gratuita, schede allenamento e community',
    icon: Dumbbell,
    defaultCtaLabel: 'Orario Corsi & Iscrizioni',
    badgeLabel: 'Fitness & Gym',
  },
  {
    id: 'retail',
    label: 'Abbigliamento & Moda',
    categoryGroup: 'retail',
    groupLabel: 'Retail & Shopping',
    desc: 'Ruota sconti al registratore di cassa, nuove collezioni e fidelity',
    icon: ShoppingBag,
    defaultCtaLabel: 'Nuova Collezione & Sconti',
    badgeLabel: 'Fashion & Abbigliamento',
  },
  {
    id: 'store',
    label: 'Negozio & Bottega',
    categoryGroup: 'retail',
    groupLabel: 'Retail & Shopping',
    desc: 'Offerte del mese, ruota della fortuna e passaparola Google',
    icon: Store,
    defaultCtaLabel: 'Catalogo & Offerte',
    badgeLabel: 'Bottega & Dettaglio',
  },
  {
    id: 'professional',
    label: 'Studio Professionale',
    categoryGroup: 'services',
    groupLabel: 'Servizi & Professioni',
    desc: 'Avvocati, commercialisti, consulenti aziendali: contatti e appuntamenti',
    icon: Briefcase,
    defaultCtaLabel: 'Richiedi Consulenza',
    badgeLabel: 'Studio Professionale',
  },
  {
    id: 'automotive',
    label: 'Concessionaria & Officina',
    categoryGroup: 'services',
    groupLabel: 'Servizi & Professioni',
    desc: 'Prenotazione tagliando, revisione rapida e test drive',
    icon: Car,
    defaultCtaLabel: 'Prenota Tagliando / Test Drive',
    badgeLabel: 'Automotive',
  },
  {
    id: 'nightlife',
    label: 'Club & Lounge Bar',
    categoryGroup: 'food',
    groupLabel: 'Food & Beverage',
    desc: 'Cocktail list interattiva, prenotazione tavoli/privé ed eventi',
    icon: Music,
    defaultCtaLabel: 'Cocktail List & Privé',
    badgeLabel: 'Club & Lounge',
  },
  {
    id: 'generic',
    label: 'Servizi Generali & Artigiani',
    categoryGroup: 'services',
    groupLabel: 'Servizi & Professioni',
    desc: 'Piattaforma modulare personalizzabile per qualsiasi tipo di attività',
    icon: Layers,
    defaultCtaLabel: 'Scopri i Nostri Servizi',
    badgeLabel: 'Attività Locale',
  },
];

export function getCategoryDefinition(id?: string | null): CategoryDefinition {
  return CATEGORIES.find((c) => c.id === id) || CATEGORIES[CATEGORIES.length - 1];
}
