import { BusinessTypeSlug, ModuleSlug } from '../modules/registry';

export type VerticalDashboardType = 'retail' | 'restaurant' | 'hospitality' | 'service';

export interface VerticalTerminology {
  catalogLabel: string;
  productLabel: string;
  inventoryLabel: string;
  salesLabel: string;
  customerLabel: string;
  orderLabel: string;
}

export interface VerticalDefinition {
  slug: BusinessTypeSlug;
  name: string;
  shortName: string;
  description: string;
  iconName: string;
  categoryGroup: 'retail' | 'food' | 'hospitality' | 'wellness' | 'services';
  dashboardType: VerticalDashboardType;
  defaultModules: ModuleSlug[];
  requiredModules: ModuleSlug[];
  recommendedModules: ModuleSlug[];
  terminology: VerticalTerminology;
  sortOrder: number;
}

export const VERTICAL_REGISTRY: Record<BusinessTypeSlug, VerticalDefinition> = {
  retail: {
    slug: 'retail',
    name: 'Retail & Boutique',
    shortName: 'Retail',
    description: 'Negozi di abbigliamento, accessori, pelletteria e punti vendita commerciali',
    iconName: 'ShoppingBag',
    categoryGroup: 'retail',
    dashboardType: 'retail',
    defaultModules: [
      'analytics',
      'products',
      'inventory',
      'sales',
      'crm',
      'suppliers',
      'loyalty',
      'nfc_qr',
      'review_shield',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'products'],
    recommendedModules: ['inventory', 'sales', 'suppliers', 'crm', 'loyalty'],
    terminology: {
      catalogLabel: 'Catalogo & Capi',
      productLabel: 'Articolo / Prodotto',
      inventoryLabel: 'Giacenze & Taglie',
      salesLabel: 'Cassa & Vendite',
      customerLabel: 'Clienti',
      orderLabel: 'Ordini Fornitori',
    },
    sortOrder: 10,
  },
  shoe_store: {
    slug: 'shoe_store',
    name: 'Calzature & Accessori',
    shortName: 'Scarpe',
    description: 'Negozi di scarpe, sneakers, borse e accessori moda con gestione taglie numeriche',
    iconName: 'Footprints',
    categoryGroup: 'retail',
    dashboardType: 'retail',
    defaultModules: [
      'analytics',
      'products',
      'inventory',
      'sales',
      'crm',
      'suppliers',
      'loyalty',
      'nfc_qr',
      'review_shield',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'products'],
    recommendedModules: ['inventory', 'sales', 'suppliers', 'crm', 'loyalty'],
    terminology: {
      catalogLabel: 'Catalogo Calzature',
      productLabel: 'Scarpa / Modello',
      inventoryLabel: 'Giacenze & Numerazioni',
      salesLabel: 'Cassa & Scontrini',
      customerLabel: 'Clienti',
      orderLabel: 'Riordini & Fornitori',
    },
    sortOrder: 15,
  },
  restaurant: {
    slug: 'restaurant',
    name: 'Ristorante & Bistrot',
    shortName: 'Ristorante',
    description: 'Esperienze culinarie complete, menu digitale, gestione comande e coperti al tavolo',
    iconName: 'UtensilsCrossed',
    categoryGroup: 'food',
    dashboardType: 'restaurant',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'loyalty',
      'coupons',
      'smart_router',
      'universal_hub',
      'table_service',
      'staff',
      'service_calls',
      'canva_menu',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['table_service', 'service_calls', 'canva_menu', 'loyalty', 'review_shield'],
    terminology: {
      catalogLabel: 'Menù & Carte',
      productLabel: 'Piatto / Specialità',
      inventoryLabel: 'Dispensa & Cantina',
      salesLabel: 'Conti & Coperti',
      customerLabel: 'Ospiti al Tavolo',
      orderLabel: 'Comande Cucina',
    },
    sortOrder: 20,
  },
  bar: {
    slug: 'bar',
    name: 'Bar & Caffetteria',
    shortName: 'Bar',
    description: 'Colazioni, listini rapidi, caffetteria, fidelity card e Wi-Fi',
    iconName: 'Coffee',
    categoryGroup: 'food',
    dashboardType: 'restaurant',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'loyalty',
      'coupons',
      'smart_router',
      'universal_hub',
      'table_service',
      'staff',
      'service_calls',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['loyalty', 'coupons', 'review_shield'],
    terminology: {
      catalogLabel: 'Listino & Snack',
      productLabel: 'Consumazione',
      inventoryLabel: 'Scorte Banco',
      salesLabel: 'Scontrini Banco',
      customerLabel: 'Clienti Frequenti',
      orderLabel: 'Ordini Fornitori',
    },
    sortOrder: 30,
  },
  pizzeria: {
    slug: 'pizzeria',
    name: 'Pizzeria & Pub',
    shortName: 'Pizzeria',
    description: 'Pizze tonde, birre alla spina, gestione ranghi sala e sconti',
    iconName: 'Pizza',
    categoryGroup: 'food',
    dashboardType: 'restaurant',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'loyalty',
      'coupons',
      'smart_router',
      'universal_hub',
      'table_service',
      'staff',
      'service_calls',
      'canva_menu',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['table_service', 'canva_menu', 'loyalty'],
    terminology: {
      catalogLabel: 'Menù Pizze & Birre',
      productLabel: 'Pizza / Bevanda',
      inventoryLabel: 'Giacenze Forno & Fusti',
      salesLabel: 'Conti & Tavoli',
      customerLabel: 'Clienti',
      orderLabel: 'Comande Forno',
    },
    sortOrder: 40,
  },
  gelateria: {
    slug: 'gelateria',
    name: 'Gelateria & Pasticceria',
    shortName: 'Gelateria',
    description: 'Gusti artigianali, allergeni, ruota premi e tessere fedeltà',
    iconName: 'IceCream',
    categoryGroup: 'food',
    dashboardType: 'service',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'loyalty',
      'coupons',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['loyalty', 'coupons', 'review_shield'],
    terminology: {
      catalogLabel: 'Gusti & Carapine',
      productLabel: 'Gusto / Dessert',
      inventoryLabel: 'Ingredienti',
      salesLabel: 'Scontrini Cassa',
      customerLabel: 'Clienti',
      orderLabel: 'Ordini Laboratorio',
    },
    sortOrder: 50,
  },
  hotel: {
    slug: 'hotel',
    name: 'Hotel & Resort',
    shortName: 'Hotel',
    description: 'Room directory, servizi concierge, info turistiche e promozioni interne',
    iconName: 'Building2',
    categoryGroup: 'hospitality',
    dashboardType: 'hospitality',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'universal_hub',
      'staff',
      'service_calls',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['service_calls', 'review_shield', 'universal_hub'],
    terminology: {
      catalogLabel: 'Servizi & Camere',
      productLabel: 'Servizio Concierge',
      inventoryLabel: 'Forniture Camere',
      salesLabel: 'Addebiti Camera',
      customerLabel: 'Ospiti Hotel',
      orderLabel: 'Richieste Ospiti',
    },
    sortOrder: 60,
  },
  bb: {
    slug: 'bb',
    name: 'B&B & Guest House',
    shortName: 'B&B',
    description: 'Check-in digitale, guida della città, Wi-Fi 1-Tap e consigli locali',
    iconName: 'Home',
    categoryGroup: 'hospitality',
    dashboardType: 'hospitality',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['review_shield', 'universal_hub'],
    terminology: {
      catalogLabel: 'Guida & Convenzioni',
      productLabel: 'Esperienza / Servizio',
      inventoryLabel: 'Kit Cortesia',
      salesLabel: 'Prenotazioni Extra',
      customerLabel: 'Ospiti B&B',
      orderLabel: 'Check-in',
    },
    sortOrder: 70,
  },
  gym: {
    slug: 'gym',
    name: 'Palestra & Fitness Club',
    shortName: 'Fitness',
    description: 'Orari corsi, pass digitali, piani abbonamento e promozioni',
    iconName: 'Dumbbell',
    categoryGroup: 'wellness',
    dashboardType: 'service',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'loyalty',
      'coupons',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['loyalty', 'crm', 'coupons'],
    terminology: {
      catalogLabel: 'Abbonamenti & Corsi',
      productLabel: 'Pacchetto Corsi',
      inventoryLabel: 'Accessori & Integratori',
      salesLabel: 'Rinnovi & Iscrizioni',
      customerLabel: 'Iscritti & Atleti',
      orderLabel: 'Prenotazioni Corsi',
    },
    sortOrder: 80,
  },
  medical_studio: {
    slug: 'medical_studio',
    name: 'Studio Medico & Sanitario',
    shortName: 'Studio Medico',
    description: 'Orari visite, prenotazione appuntamenti e documentazione informativa',
    iconName: 'Stethoscope',
    categoryGroup: 'services',
    dashboardType: 'service',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'nfc_qr', 'universal_hub'],
    recommendedModules: ['crm', 'review_shield'],
    terminology: {
      catalogLabel: 'Prestazioni Mediche',
      productLabel: 'Visita / Trattamento',
      inventoryLabel: 'Materiale Sanitario',
      salesLabel: 'Fatture Prestazioni',
      customerLabel: 'Pazienti',
      orderLabel: 'Appuntamenti',
    },
    sortOrder: 90,
  },
  other: {
    slug: 'other',
    name: 'Attività Commerciale Generica',
    shortName: 'Attività',
    description: 'Configurazione modulare e flessibile per qualsiasi punto vendita o attività',
    iconName: 'Store',
    categoryGroup: 'services',
    dashboardType: 'service',
    defaultModules: [
      'analytics',
      'crm',
      'nfc_qr',
      'review_shield',
      'loyalty',
      'universal_hub',
    ],
    requiredModules: ['analytics', 'nfc_qr'],
    recommendedModules: ['loyalty', 'crm', 'universal_hub'],
    terminology: {
      catalogLabel: 'Servizi & Prodotti',
      productLabel: 'Articolo / Servizio',
      inventoryLabel: 'Giacenze',
      salesLabel: 'Transazioni',
      customerLabel: 'Clienti',
      orderLabel: 'Ordini',
    },
    sortOrder: 100,
  },
};

export function getVertical(slug: BusinessTypeSlug): VerticalDefinition {
  return VERTICAL_REGISTRY[slug] || VERTICAL_REGISTRY.other;
}
